name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    name: deploy to cluster 
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      uses: actions/checkout@master
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: build and push to docker
      uses: docker/build-push-action@v6
      with:
        context: prueba-3
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}