name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
    paths:
      - prueba-3/index.html
env:
  AWS_REGION: us-east-1
  ECS_SERVICE: app-nginx
  ECS_CLUSTER: cluster-010101
  ECS_TASK_DEFINITION: nginx-task 
jobs:
  deploy:
    name: deploy to cluster 
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: build and push to docker
      uses: docker/build-push-action@v6
      with:
        context: prueba-3
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY }}:latest
    - 
      name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    -
      name: Update ECS
      run: |
        aws ecs update-service \
          --cluster  ${{ env.ECS_CLUSTER }} \
          --service ${{ env.ECS_SERVICE }} \
          --task-definition ${{ env.ECS_TASK_DEFINITION }}:${{ env.SHA }} \
          --force-new-deployment